require("craftycatz.options")
require("craftycatz.keymap")
require("craftycatz.plugin")
require("craftycatz.treesitter")
require("craftycatz.cmp")
require("craftycatz.lspconfig")
require("craftycatz.lualine")
require("craftycatz.lspkind")
require("craftycatz.lsp-colors")
require("craftycatz.mason")
require("craftycatz.bufferline")
require("craftycatz.poimandres")
require("craftycatz.telescope")
require("craftycatz.ts-autotag")
require("craftycatz.lspsaga")
require("craftycatz.autopairs")
require("craftycatz.null-ls")

vim.cmd("colorscheme poimandres")